### PR TITLE
binMaxHead constraint, head binarity for japanese compounds

### PR DESCRIPTION
**Pull request by ivpetkov**
Issue #276

### CODE REVIEW

**Comment by jbellik** [comment]
Once we merge Max's pull request, this should also call the mark heads function markHeadsJapanese.

**Comment by jbellik** [comment]
@ivpetkov You can update from master now to get Max's head marking function.

**Comment by ivpetkov** [comment]
I just added the function call, but I didn't merge his branch into mine so I haven't actually tested it. Should I merge his branch into this one or should I wait for his to be merged into master and then merge into this one?

**Comment by jbellik** [comment]
Oops apparently we commented at the exact same time!

**Comment by ivpetkov** [comment]
Haha 😂ok I'll update from master

**Pull request merged**
