### PR TITLE
inital reorganize. Gen options moved to top. Combined string input se…

### PR DESCRIPTION
**Pull request by ColinAChen**
…ctions. Removed tree builder section from bottom. Added divider lines with extra padding in between new sections. First input area should correctly be used for gen options.

### CODE REVIEW

**Comment by ColinAChen** [comment]
The most recent commit should restore functionality to the Build Tree button

**Comment by jbellik** [comment]
Much better. But it's still somewhat confusing in that clicking "Generate tree" doesn't automatically open the tree-builder. I'd actually like to eliminate the "Open tree builder" button altogether, and have the tree builder open when "Generate tree" is clicked.

**Comment by ColinAChen** [comment]
The "open tree builder" button should be removed and the tree builder menu should open when "generate tree" is clicked.

**Comment by jbellik** [comment]
Looking good. Can I ask for two more changes?
1. Rename "Generate tree" to "Build syntax"
2. Create another button next to it called "Run GEN" that does the same thing as the "Get results" button.
Thanks!

**Comment by ColinAChen** [comment]
Both of the changes should be implemented!

**Pull request merged**
