### PR TITLE
Match Automated Testing

### PR DESCRIPTION
**Pull request by maxTarlov**
@M130 and I finished turning @nvh4 's test methods into automated tests using mocha. There is still some naming of tests to occur, but personally I would like feedback before editing all of the names.

Proposed naming scheme: describe blocks are labeled according to their corresponding tableau in @nvh4 's file, followed by a colon, followed by the syntax parameters (if any) that are being held constant in that test block. It blocks are named according to the varied prosody parameters.

Example:
## Tableau 10: nonMinSyntax
 - [X] maxProsody
 - [X] nonMaxProsody
 - [X] minProsody
    ...

### CODE REVIEW

**Comment by jbellik** [comment]
This looks great! I agree the names need some work for transparency. A first step will be to include the bracket representation of both the stree and ptrees in the text for each it(), I think. Or if the trees are the same within each block, the bracket representations could go in the describe() statements.

**Comment by jbellik** [comment]
Other naming improvements can be made too but let's discuss them during the meeting tomorrow

**Comment by maxTarlov** [comment]
> A first step will be to include the bracket representation of both the stree and ptrees in the text for each it(), I think. Or if the trees are the same within each block, the bracket representations could go in the describe() statements.

The same stree is used for every assertion, but each "it" block uses at least two ptrees, and most use about 6. Maybe instead of putting the bracket representation of all 3-6 trees in the it block, we can show the trees in the message of each assertion. In this case, you would only see a tree if an assertion fails. 

(If you look at @nvh4 's tests, each "describe" block is a tableau and each "it" block is a constraint column in that tableau.)

**Comment by jbellik** [comment]
That sounds like a good solution.

**Comment by maxTarlov** [comment]
I have implemented a version of the above proposal for Tableau 1. To see it in action, pick an arbitrary assertion in the first describe block and change the expected value.

**Comment by jbellik** [comment]
Add README type info at the top, including references to Nick Van Handel's files & possibly blocks of his text from the pdf file.

**Pull request merged**
